#!/bin/sh

#BSPWM configuration

bspc config border_width         2
bspc config window_gap           8
bspc config top_padding          5
bspc config bottom_padding       60
bspc config left_padding         5
bspc config right_padding        5
bspc config single_monocle       false
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

#BSPWM coloring
bspc config normal_border_color "#8ba8a4"
bspc config active_border_color "#8ba8a4"
bspc config focused_border_color "#8ba8a4"
bspc config presel-feedback_colour "#8ba8a4"


#Single monitor
bspc monitor -d 1 2 3 4 5

# Start programs

function run {
  if ! pgrep $1 ;
  then
    $@&
  fi
}

xset r rate 300 30
xinput set-prop 10 'libinput Accel Speed' -0.4

rm $HOME/.cache/dunst.log
rm -r $HOME/.cache/dunst/

$HOME/.config/polybar/launch.sh &
run sxhkd -c ~/.config/bspwm/sxhkdrc &
feh --bg-fill /home/solid/Pictures/walls/Home.png & 
xsetroot -cursor_name left_ptr &
numlockx off &
picom --config $HOME/.config/bspwm/picom.conf &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
run redshift &
run polybar &
run dunst &
